"""added unique constraint on event

Revision ID: 1f53dfb14396
Revises: ad09d94ffe59
Create Date: 2024-06-29 16:24:29.268619

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1f53dfb14396"
down_revision = "ad09d94ffe59"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "name_lat_long_uix", "events", ["name", "location_lat", "location_long"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("name_lat_long_uix", "events", type_="unique")
    # ### end Alembic commands ###
