"""added version on event table

Revision ID: 367fb1e8c29c
Revises: b0261c1e5105
Create Date: 2024-09-28 16:48:19.087321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '367fb1e8c29c'
down_revision = 'b0261c1e5105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'version')
    # ### end Alembic commands ###
