"""added unique constraint on user

Revision ID: 4baeeb73f8c9
Revises: 1f53dfb14396
Create Date: 2024-06-29 16:43:14.162560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baeeb73f8c9'
down_revision = '1f53dfb14396'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('phone_number_uix', 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('phone_number_uix', 'users', type_='unique')
    # ### end Alembic commands ###
