"""updated payment table

Revision ID: b1a8f6d0eac5
Revises: 459a25099614
Create Date: 2024-07-07 21:55:35.963053

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b1a8f6d0eac5"
down_revision = "459a25099614"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("idempotency_key", sa.String(), nullable=False))
    op.alter_column(
        "payments",
        "transaction_id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE payments ALTER COLUMN transaction_id TYPE UUID USING transaction_id::uuid"
    )
    op.drop_column("payments", "idempotency_key")
    # ### end Alembic commands ###
