"""added constraints on payments table

Revision ID: d76ae127b951
Revises: b1a8f6d0eac5
Create Date: 2024-07-07 23:42:49.303176

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d76ae127b951"
down_revision = "b1a8f6d0eac5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("transaction_id_idx", "payments", ["transaction_id"], unique=False)
    op.create_unique_constraint("transaction_id_uix", "payments", ["transaction_id"])
    op.create_unique_constraint("idempotency_key_uix", "payments", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("idempotency_key_uix", "payments", type_="unique")
    op.drop_constraint("transaction_id_uix", "payments", type_="unique")
    op.drop_index("transaction_id_idx", table_name="payments")
    # ### end Alembic commands ###
