"""updated keycloak_id nullablity constraint

Revision ID: f71b7f69f1f4
Revises: 367fb1e8c29c
Create Date: 2024-09-30 11:14:15.966281

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f71b7f69f1f4"
down_revision = "367fb1e8c29c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "keycloak_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "keycloak_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
